### ISSUE TITLE
ROS Package Collections

### ISSUE THREAD

**Issue by doganulus** [bpwilcox/ros2-production-working-group#11]
### Proposal Description:

This proposal targets multi-package ROS projects and aims to streamline build and dependency management for basic and advanced use cases. In the following, we call a multi-package ROS project a ROS package collection and treat it as a single entity to manage. 

A ROS package collection is assumed to be developed on a single version-controlled online repository by a single organization. We assume that the `<hostname>/<organization>/<collection_name>` uniquely identifies the collection. The organization has full control over all packages in the collection.

The proposal places package collections between package and system levels in the hierarchy as follows:
  - Node executable
  - Package
  - **Collection**
  - System

The proposal includes a motivation for ROS package collections and defines a collection manifest specification that declares dependencies, environments, and other metadata at the collection level. Initially, we consider the following features under this task proposal issue:

- Multiple environment declarations per collection 
    - `default`, `runtime`, `build`, `devel`, `test`, and developer-defined environments
- Multi-tool dependency declaration per environment 
    - Explicit use of `rosdep`, `apt`, `apt_repository`, `pip`, `cargo`, `cmake`, `shell`, ...
    - Encourage the use of existing formats like `requirements.txt` and `cargo.toml`
- Override semantics for configuration options at global, environment, tool, and unit levels
- Third-party source repositories are integrated into the collection specification
- Single-file collection specification for basic use cases (top-level `collection.yml`)
- Multi-file collection specification for advanced use cases (top-level `collection` folder)
- Custom standardized script (verb) declaration per collection such as `build`, `test`
  
The proposal does not include a reference implementation. It initially aims to increase the understanding of production requirements, discuss semantics and mechanisms, and reach an easily implementable specification.
 
### Estimated Effort:
(2 months) Requirements elicitation and schema specification 
  
### Area of Impact:
Build, testing, distribution, deployment.
  
### Related Works:
- ROS package manifests [1](https://ros.org/reps/rep-0127.html), [2](https://ros.org/reps/rep-0140.html), [3](https://ros.org/reps/rep-0149.html)
- ROS meta-packages 
- [ROS variants](https://www.ros.org/reps/rep-2001.html)
- [Devcontainers](https://containers.dev/)
- [Ansible execution environments](https://ansible.readthedocs.io/en/latest/getting_started_ee/build_execution_environment.html)

**Comment by doganulus** [comment]
## Collection Manifest

The proposal introduces top-level `collection.yml` file to specify environments, dependencies, and collection metadata. 

The `collection.yml` is equivalent to `package.xml` at the collection level. The relation between package and collection manifests will be discussed later.

The full specification will be defined in [JSON Schema](https://json-schema.org/). Below are some examples demonstrating the structure of collection manifests.

#### First example

```yaml
# collection.yml

organization: "my_company"
name: "my_ros_collection"
description: "describe the collection"
version: "1"

depends:
  rosdep: # tool or package manager name is explicit 
    packages: [boost, other-rosdep-key] # list multiple rosdep keys here
```

#### Single collection file with multiple environments

```yaml
# collection.yml

environments:
  runtime:
    depends: 
      # Declare collection runtime (exec) dependencies using rosdep keys
      rosdep: [...]
      
  build:
    extends: [runtime] # depends on everything the runtime environment depends on
    depends:
      # Declare build dependencies using rosdep keys
      rosdep: [...]
      
  devel:
    extends: [build] # depends on everything the build environment depends on
    depends:
      # Declare extra development dependencies using rosdep keys
      rosdep: [...] 
```

#### More advanced collection file with multiple environments

```yaml
# collection.yml

environments:
  runtime:
    depends: 
      apt: 
        packages: [libboost-dev, libssl] 
      yum:
        packages: []
      pip:
        packages_file: requirements.txt # file spec
      cargo:
        packages_file: cargo.toml # file spec
      zypper:
        packages: []
    
  build:
    extends: [runtime]
    depends:
      apt: 
        packages: [g++, cmake]
        options: # Override global apt options
      cmake:
        # repositories functionality integrated here and expanded
        # fetch using git and build with cmake default options
        # Makefile or meson based repositories goes under their key
        repositories: 
          - repo: github.com/other_organization/other_repo
            dest: /tmp/
            version: main
            options:
              git: # Override global git options at unit level if desired
              cmake: # Override global cmake options at unit level if desired
              
    options:
      git: # Override global git options at environment level if desired
      cmake: # Override global cmake options at environment level if desired 
      
  # developers can define custom environments 
  my_devel_extra:
    container: 
      image: ros:humble # specify a development container image 
      # build: # or build a container locally <see docker.compose.services.build>
      #   dockerfile: ./Dockerfile
    extends: [build]
    depends: 
      pip: 
        packages: ["numpy>=1.4", "scipy==2.12"]

  # default environment is inherited automatically by others
  # top-level depends element resolves to environments.default.depends
  default: 
    depends: 
      apt: [] # list default apt dependencies here

# Top-level options will be passed to individual tools. 
# These options may be overridden at environment and unit levels if applicable.
options: 
  apt:
    update: true
  git:
    clone: true
    recursive: true
    depth: 1
    
# Top-level options will be passed to individual tools. 
# Similar to package.json/scripts elements
commands:
  build: colcon build
  test: colcon test
```


#### Multi-file collection specification 

Production environments may require multiple and experimental environments with many customizations. In these cases, a multi-file layout can be more managable. The multi-file layout for collections are as follows:  

```
.
|-- collection.yml
|-- environments
|   |-- default.yml
|   |-- runtime.yml
|   |-- build.yml
|   |-- devel.yml
|   |-- test1.yml
|   |-- test2.yml
|   |-- ...
|   |-- testN.yml
|
|-- packages
    |-- package_1/
    |-- package_2/
```

#### Multi-file environment specification 

Even more...

```
.
|-- collection
|   |-- main.yml
|   |-- options.yml
|   |-- environments
|       |-- default
|           |-- main.yml
|           |-- options.yml
|           |-- Containerfile
|       |-- runtime
|           |-- main.yml
|           |-- options.yml
|           |-- Containerfile
|       |-- build
|           |-- main.yml
|           |-- options.yml
|           |-- requirements.txt
|           |-- Containerfile
|       |-- devel
|           |-- main.yml
|           |-- options.yml
|           |-- requirements.txt
|           |-- Containerfile
|
|-- packages
    |-- package_1/
    |-- package_2/
```
